# Generated by Django 4.2.6 on 2023-10-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_portfolio_status_portfolio_work_delete_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_portfolio_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_date', models.CharField(max_length=50)),
                ('anytext', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('img_vid', models.BooleanField(default=False)),
                ('img', models.ImageField(null=True, upload_to='assets/images/')),
                ('vid', models.FileField(null=True, upload_to='assets/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='home_portfolio_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('img_vid', models.BooleanField(default=False)),
                ('img', models.ImageField(null=True, upload_to='assets/images/')),
                ('vid', models.FileField(null=True, upload_to='assets/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='people_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('img', models.ImageField(null=True, upload_to='assets/images/')),
            ],
        ),
    ]
